// Major US cities by state abbreviation (for city dropdown in checkout).
const CITY_MAP: Record<string, string[]> = {
  AL: ["Birmingham","Montgomery","Mobile","Huntsville","Tuscaloosa"],
  AK: ["Anchorage","Fairbanks","Juneau","Sitka","Ketchikan"],
  AZ: ["Phoenix","Tucson","Mesa","Chandler","Scottsdale","Tempe"],
  AR: ["Little Rock","Fort Smith","Fayetteville","Springdale","Jonesboro"],
  CA: ["Los Angeles","San Diego","San Jose","San Francisco","Fresno","Sacramento","Long Beach","Oakland","Bakersfield","Anaheim","Santa Ana","Riverside"],
  CO: ["Denver","Colorado Springs","Aurora","Fort Collins","Lakewood","Boulder"],
  CT: ["Hartford","New Haven","Stamford","Bridgeport","Waterbury"],
  DE: ["Wilmington","Dover","Newark","Middletown"],
  FL: ["Miami","Orlando","Tampa","Jacksonville","Fort Lauderdale","Hialeah","Tallahassee","St. Petersburg","Hollywood"],
  GA: ["Atlanta","Augusta","Columbus","Savannah","Athens","Macon","Sandy Springs"],
  HI: ["Honolulu","Hilo","Kailua","Pearl City"],
  ID: ["Boise","Nampa","Meridian","Idaho Falls","Pocatello"],
  IL: ["Chicago","Aurora","Rockford","Joliet","Naperville","Springfield","Peoria"],
  IN: ["Indianapolis","Fort Wayne","Evansville","South Bend","Carmel","Bloomington"],
  IA: ["Des Moines","Cedar Rapids","Davenport","Sioux City","Iowa City"],
  KS: ["Wichita","Kansas City","Overland Park","Olathe","Topeka"],
  KY: ["Louisville","Lexington","Bowling Green","Owensboro","Covington"],
  LA: ["New Orleans","Baton Rouge","Shreveport","Lafayette","Lake Charles"],
  ME: ["Portland","Lewiston","Bangor","South Portland","Auburn"],
  MD: ["Baltimore","Columbia","Germantown","Silver Spring","Waldorf"],
  MA: ["Boston","Worcester","Springfield","Cambridge","Lowell","Quincy"],
  MI: ["Detroit","Grand Rapids","Warren","Sterling Heights","Ann Arbor","Lansing","Flint"],
  MN: ["Minneapolis","Saint Paul","Rochester","Bloomington","Duluth"],
  MS: ["Jackson","Gulfport","Southaven","Hattiesburg","Biloxi"],
  MO: ["Kansas City","Saint Louis","Springfield","Columbia","Independence"],
  MT: ["Billings","Missoula","Great Falls","Bozeman","Helena"],
  NE: ["Omaha","Lincoln","Bellevue","Grand Island","Kearney"],
  NV: ["Las Vegas","Henderson","Reno","North Las Vegas","Sparks"],
  NH: ["Manchester","Nashua","Concord","Dover","Rochester"],
  NJ: ["Newark","Jersey City","Paterson","Elizabeth","Edison","Trenton"],
  NM: ["Albuquerque","Las Cruces","Rio Rancho","Santa Fe","Roswell"],
  NY: ["New York City","Buffalo","Rochester","Yonkers","Syracuse","Albany","New Rochelle","Mount Vernon"],
  NC: ["Charlotte","Raleigh","Greensboro","Durham","Winston-Salem","Fayetteville","Cary"],
  ND: ["Fargo","Bismarck","Grand Forks","Minot","West Fargo"],
  OH: ["Columbus","Cleveland","Cincinnati","Toledo","Akron","Dayton"],
  OK: ["Oklahoma City","Tulsa","Norman","Broken Arrow","Edmond"],
  OR: ["Portland","Salem","Eugene","Gresham","Hillsboro"],
  PA: ["Philadelphia","Pittsburgh","Allentown","Erie","Reading","Scranton"],
  RI: ["Providence","Warwick","Cranston","Pawtucket","East Providence"],
  SC: ["Columbia","Charleston","North Charleston","Mount Pleasant","Greenville"],
  SD: ["Sioux Falls","Rapid City","Aberdeen","Brookings","Watertown"],
  TN: ["Nashville","Memphis","Knoxville","Chattanooga","Clarksville"],
  TX: ["Houston","San Antonio","Dallas","Austin","Fort Worth","El Paso","Arlington","Corpus Christi","Plano","Laredo"],
  UT: ["Salt Lake City","West Valley City","Provo","West Jordan","Orem"],
  VT: ["Burlington","South Burlington","Rutland","Montpelier"],
  VA: ["Virginia Beach","Norfolk","Chesapeake","Richmond","Newport News","Alexandria"],
  WA: ["Seattle","Spokane","Tacoma","Vancouver","Bellevue","Everett"],
  WV: ["Charleston","Morgantown","Huntington","Parkersburg","Wheeling"],
  WI: ["Milwaukee","Madison","Green Bay","Kenosha","Racine","Appleton"],
  WY: ["Cheyenne","Casper","Laramie","Gillette"],
};

export function getCitiesByState(stateCode: string): string[] {
  return CITY_MAP[stateCode] ?? [];
}
